version: '2'

services:
    soa:
        build:
            context: ./SOA
            dockerfile: Dockerfile     
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        networks:
            local:
                ipv4_address: 192.168.0.1  
        volumes:
            - ./soa/named.conf:/etc/bind/named.conf
            - ./soa/named.conf.options:/etc/bind/named.conf.options
            - ./soa/named.conf.default-zones:/etc/bind/named.conf.default-zones
        container_name: mysoa
        
    resolveur:
        build:
            context: ./resolveur
            dockerfile: Dockerfile     
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        networks:
            local:
                ipv4_address: 192.168.0.2  
        volumes:
            - ./soa/named.conf:/etc/bind/named.conf
        container_name: resolv