FROM ubuntu:16.04

RUN apt-get update && apt-get -y install asterisk
RUN apt -y install git curl wget libnewt-dev libssl-dev libncurses5-dev subversion  libsqlite3-dev build-essential libj>

WORKDIR /etc/asterisk

EXPOSE 5060